[package]
name = "gpterm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
crossterm = "0.25"

tokio = "1.26.0"
async-openai = "0.9.4"
textwrap = "0.16.0"
arboard = "3.2.0"